name: ikuyo-publish-release

on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        description: "Version Label"
      description:
        description: "Release description"
      prerelease:
        description: "Pre-release"
        type: boolean
        default: false

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Wait for previous workflow completion
        uses: ArcticLampyrid/action-wait-for-workflow@v1
        with:
          workflow: build.yml
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v20
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          workflow_search: true
          workflow_conclusion: success
          path: artifacts
          skip_unpack: true
      - name: Enumerate artifacts
        run: ls -A ./artifacts
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          working_directory: artifacts
          files: '*.zip'
          generate_release_notes: true
          body: ${{ github.event.inputs.description }}
          tag_name: ${{ github.event.inputs.version }}
          prerelease: ${{ github.event.inputs.prerelease }}
          make_latest: true
          
